---
title: "R Notebook"
output: html_notebook
---

```{r, include=FALSE}
library(data.table)
library(dplyr)
library(lmtest)
library(sandwich)
library(stargazer)
library(pwr)
```
 

```{r data}
data <- fread("../data/processed/analysis_table.csv")

data[, treat_ind := ifelse(treat=='t',1,0)]

data[, treat_with_logo := ifelse((logo != 'none' & treat == 't'),1 ,0)]

data[, tjs_logo := ifelse(test = grepl(pattern = "tjs", data[, logo]),
                                              yes = 1, no = 0)]

data[, nike_logo := ifelse(test = grepl(pattern = "nike", data[, logo]),
                                              yes = 1, no = 0)]

data[, no_logo := ifelse(test = grepl(pattern = "none", data[, logo]),
                                              yes = 1, no = 0)]
data[, survey_block := gsub("^.*_", "", data$photo_block)]

names(data)
```

```{r}
model_1 <- lm(total_counts ~ tjs_logo + survey_block, data)
=======
View(data)
```

```{r histograms}
hist(data[data$tjs_logo==1]$total_counts)
hist(data[data$treat_ind==0]$total_counts)
hist(data[data$nike_logo==1]$total_counts)

data[smile == 'smile', hist(total_counts)]
data[smile == 'nonsmile', hist(total_counts)]
```

```{r baseline}
model <- lm(total_counts ~ tjs_logo + survey_block, data)


```


```{r blocks}
#model2 <- lm(total_counts ~ tjs_logo*treat_ind*survey_block, data)
#summary(model2)
model2 <- lm(total_counts ~ tjs_logo + tjs_logo*survey_block, data)
summary(model2)
```

```{r placebo design}
cace_subset_model <- data[nike_logo ==  0, lm(total_counts ~ tjs_logo)]
summary(cace_subset_model)
```


```{r smile model}
smile_model <- data[, lm(total_counts ~ tjs_logo + smile)]
summary(smile_model)

#power calculation
pwr.f2.test(u = 3, v = 211, f2 = 0.01669)
```


```{r}
interim <- data[logo != "nike"]
# View(interim)
tjs_only <- data[logo == "tjs"]
View(tjs_only)

photo_name_split <- read.table(text = interim[ , photo_block], sep = "_", as.is = TRUE, fill = TRUE)
interim[, join_id := paste(photo_name_split$V1, photo_name_split$V2, photo_name_split$V3, photo_name_split$V6, photo_name_split$V7, sep="_")]

# View(interim)
tjs_only <- interim[logo=="tjs"]
tjs_only <- tjs_only[ , c("photo_block", "join_id", "treat_ind", "survey_block", "total_counts", "smile")]
rows_to_keep <- tjs_only[, join_id]
none_c_only <- interim[logo=="none" & treat_ind<1]
none_c_only <- none_c_only[ , c("photo_block", "join_id", "treat_ind", "survey_block", "total_counts", "smile")]
none_c_matched <- subset(none_c_only, join_id %in% rows_to_keep)



# none_c_rows <- none_c_matched[, join_id]
# tjs_issue <- subset(tjs_only, !(join_id %in% none_c_rows))

# View(none_c_matched)
tjs_vs_control <- rbind(tjs_only, none_c_only)



```

```{r t-tests}
tjs_vs_nike <- data[, t.test(data[tjs_logo == 1, total_counts], data[nike_logo == 1, total_counts])]
tjs_vs_nike
tjs_vs_control <- data[, t.test(data[tjs_logo == 1, total_counts], data[tjs_logo == 0, total_counts], paired = T)] #attempt to make these paired later
tjs_vs_control
nike_vs_control <- data[, t.test(data[nike_logo == 1, total_counts], data[nike_logo == 0, total_counts])]
nike_vs_control
smile_vs_nonsmile <- data[, t.test(data[smile == 'smile', total_counts], data[smile == 'nonsmile', total_counts])]
smile_vs_nonsmile
```
